# Generated by Django 3.1.5 on 2021-01-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('place_id', models.CharField(blank=True, max_length=255)),
                ('longitude', models.FloatField(default=0, verbose_name='долгота')),
                ('latitude', models.FloatField(default=0, verbose_name='широта')),
                ('details_url', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
